# Generated by Django 4.0.5 on 2022-06-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact_details',
            field=models.JSONField(blank=True),
        ),
    ]
